### ISSUE TITLE
Publish Grails 2.0 compatible version to grails.org

### ISSUE THREAD

**Issue by kimble** [multi-tenant/grails-multi-tenant-single-db#10]
- w/ short description and link to documentation 
- Hibernate Hijacker and Hawk Eventing
- Git tag

**Comment by sronderos** [comment]
Does any more development need to be completed before the plugin is ready for 2.0?

I've been using the latest from trunk for awhile and it seems to be OK with Grails 2.0.0.

**Comment by kimble** [comment]
Not to my knowledge, but keep in mind that I'm not using it. Feel free to publish it to grails.org if you have time!

**Comment by sronderos** [comment]
I don't know how to tag in git.  I'll look into it a little later.  Other than that I think this is complete

**Comment by kimble** [comment]
Tagging is pretty straight forward. It's something like:
git tag -a v0.8.2 -m 'version 0.8.2 of Multi-Tenant SingleDB published to grails.org'

Btw.. hawk-eventing and hibernate-hijacker probably needs to be released to grails.org as well.

**Comment by sronderos** [comment]
I just checked the portal page:
http://grails.org/plugin/hibernate-hijacker
http://grails.org/plugin/hawk-eventing
Both the versions out there are the ones used by 0.8.2.  Do those need to be updated?

**Comment by kimble** [comment]
They've both received patches for Grails 2.0 compatibility since they were released to grails.org. Perhaps the version number hasn't been bumped yet?

**Comment by alxndrsn** [comment]
I think this is done.
