### ISSUE TITLE
Maven repo posted on grails.org doesn't exist

### ISSUE THREAD

**Issue by dbourget** [multi-tenant/grails-multi-tenant-single-db#14]
The documentation at grails.org for this plugin points to
http://m2repo.spockframework.org/snapshots/
but this repository does not exist.

**Comment by sronderos** [comment]
I'm not entirely sure how that got into the plugin page.  The plugin at version 0.8.2 does not rely on that repo (which is good since it doesn't exist).  That part of the documentation should disappear after the next release.  I don't know how to go back and edit the plugin page.

**Comment by sronderos** [comment]
Reviewing outstanding issues.  This appears to have been resolved long ago by the 0.8.3 release
