### ISSUE TITLE
Support for String tenant Id ?

### ISSUE THREAD

**Issue by ckthum** [multi-tenant/grails-multi-tenant-single-db#16]
Hi,

I would like check whether there is any plan to support String(generated by UUID) for the tenant Id ?
It seems like lots of changes have to be made.  Thx.

Regards,
Thum

**Comment by kimble** [comment]
Using strings for tenant id is probably not a good idea as the tenant id property will often be indexed (either alone or as part of a composite index).

**Comment by sronderos** [comment]
If there is no compelling reason to support this change, could we close this issue?

**Comment by sronderos** [comment]
Closing as duplicate of https://github.com/multi-tenant/grails-multi-tenant-single-db/issues/23
