### ISSUE TITLE
failing tests compile using spock-0.6

### ISSUE THREAD

**Issue by basejump** [multi-tenant/grails-multi-tenant-single-db#19]
Hey Kim and gang,
trying to get the tests to pass for this using grails 2.0.4 or 2.0.3. had to upgrade the spock ref to 0.6 from 0.6-snapshot and I am getting
/Users/basejump/source/basejump/grails-multi-tenant-single-db/test/unit/grails/plugin/multitenant/singledb/hibernate/TenantHibernateEventListenerSpec.groovy: -1: Attribute 'value' should have type 'java.lang.String'; but found type 'java.lang.Object' in @spock.lang.Unroll
 @ line -1, column -1.
/Users/basejump/source/basejump/grails-multi-tenant-single-db/test/unit/grails/plugin/multitenant/singledb/hibernate/TenantHibernateEventListenerSpec.groovy: 91: expected '{ -> ... }' to be an inline constant of type java.lang.String in @spock.lang.Unroll
 @ line 91, column 13.
       @Unroll({"Tenant id #tenantId, current tenant #currentTenantId, belongs to current tenant #belongsToCurrent"})
               ^

any ideas?

**Comment by kimble** [comment]
Could it be the improved unroll syntax? I'm wondering whether @Unroll takes a string now.  

http://docs.spockframework.org/en/latest/new_and_noteworthy.html

**Comment by basejump** [comment]
I'm not that familiar with Spock but thats what it looks like.
Even when I comment those out I end up with many failures. I'll take a look when I have some time but wanted to see if you had already dealt with this.

**Comment by basejump** [comment]
Changing the unrolls to just be a string without curlys did the trick
@Unroll("Tenant id #tenantId, current tenant #currentTenantId, belongs to current tenant #belongsToCurrent")

**Comment by kimble** [comment]
Nice! :-)
