### ISSUE TITLE
0.8.1 Tag publish

### ISSUE THREAD

**Issue by stoddn** [multi-tenant/grails-multi-tenant-single-db#8]
Hi,

Was a tag published for the 0.8.1 release?

Thanks,
Todd

**Comment by kimble** [comment]
Not to my knowledge

**Comment by sronderos** [comment]
I know that this is a year old.  I've created the 0.8.1 tag on my fork.  https://github.com/sronderos/grails-multi-tenant-single-db/tree/v0.8.1  If someone wants to merge it.

**Comment by sronderos** [comment]
Better late than never (I figured out how to merge the tag)
